#!/bin/bash

awk 'BEGIN { minx = 1000000; maxx = -1000000; miny = 1000000; maxy = -1000000; minz = 1000000; maxz = -1000000; } /^ATOM/ { x = $7; y = $8; z = $9; if (minx > x) minx = x; if (maxx < x) maxx = x; if (miny > y) miny = y; if (maxy < y) maxy = y; if (minz > z) minz = z; if (maxz < z) maxz = z; } END { printf("%.2f %.2f\n%.2f %.2f\n%.2f %.2f\n", minx, maxx, miny, maxy, minz, maxz) }' $1
